sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_305748f2c5d8_key -iv $encrypted_305748f2c5d8_iv -in k8s-ninja-adeda88a8779.json.enc -out k8s-ninja-adeda88a8779.json -d
  - curl h  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file k8s-ninja-adeda88a8779.json
  - gcloud config set project k8s-ninja
  - gcloud config set compute/zone australia-southeast1-a
  - gcloud container clusters get-credentials k8s-ninja-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t carmen0208/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run carmen0208/react-test npm test -- --coverage

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
